<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>blazor_jwt_validator_dotnet10</RootNamespace>
    <UserSecretsId>0c596642-57d9-4adb-b5ed-632fb4108962</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.11.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.11.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.20.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.11.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.AspNetCore.Mvc" />
    <Using Include="Microsoft.AspNetCore.Mvc.RazorPages" />
    <Using Include="Microsoft.AspNetCore.Components" />
    <Using Include="blazor_jwt_validator_dotnet10.Models" />
    <Using Include="blazor_jwt_validator_dotnet10.Data" /> 
  </ItemGroup>

</Project>
